import { useState } from "react";
import PageShell from "@/components/PageShell";

const STORIES = [
  {
    title: "The Butter Thief of Gokul",
    body: "In the narrow clay lanes of Gokul, where cow-dung patties dried on courtyard walls and the smell of fresh curd hung in the morning air, little Kanha would gather his band of merry friends. They would tiptoe past sleeping grandmothers, climb upon each other's small shoulders in human pyramids, and reach for the hanging matkas of fresh butter tied high on wooden rafters. The gopis would wake to find footprints of butter across their floors, and they would pretend to scold the dark-skinned boy with a pout and a stick in hand. But truly, they hid the butter higher each day only so He would come again, only so they could see that mischievous smile once more. For when Krishna steals butter, He is not stealing food — He is stealing hearts, one by one, gathering them like wildflowers. The gopis complained to Yashoda, but even she could not stay angry when those lotus eyes looked up at her with innocence deeper than the Yamuna. And so the lanes of Gokul rang with laughter, with love, with the eternal play of the One who comes not to be served, but to steal the butter of our devotion.",
  },
  {
    title: "Lifting Govardhan",
    body: "When proud Indra, king of the heavens, saw the villagers of Vrindavan preparing to worship Govardhan hill instead of him, his pride blazed like a thousand suns. He unleashed upon the peaceful hamlet a storm so terrible that trees were uprooted, cows scattered in terror, and the Yamuna swelled beyond her banks. The villagers huddled in fear, their children crying, their homes trembling beneath the fury of heaven's wrath. Then the young Krishna, barely seven years old, walked calmly to the base of the great Govardhan hill and lifted it upon the tip of His little finger as easily as one lifts a mushroom. For seven days and seven nights, the entire village — men, women, children, cows, calves, and birds — sheltered beneath that floating hill as Krishna stood unmoving, a gentle smile playing on His lips. The rain beat down in torrents, but beneath Govardhan, there was only warmth, only safety, only the shelter of divine love. Indra finally understood his folly and came down to beg forgiveness, realizing that the Lord of the universe needs no worship — He only asks for our trust. And so the villagers learned that when you surrender to Krishna, even the mightiest storm becomes a gentle shower beneath His sheltering hand.",
  },
  {
    title: "Kaliya Daman",
    body: "In the depths of the Yamuna river, where the water ran dark and poisonous, lived the terrible serpent Kaliya with his hundreds of writhing hoods and venom that turned the river black and killed every living creature for miles around. The cows would not drink from its banks, the birds would not sing in its trees, and the gopis trembled to draw water from its cursed currents. One day, the young Krishna climbed the great Kadamba tree on the riverbank and, with a playful laugh, dove straight into that poisoned water as if it were the clearest spring. He danced upon the raised hoods of the furious serpent, His feet lighter than lotus petals, while Kaliya struck again and again in vain rage. The serpent's wives, seeing their husband defeated and the Divine One dancing upon his head, came forward with folded hands and tearful eyes, begging for mercy. Krishna, whose heart is softer than butter, forgave Kaliya and sent him away to a distant ocean, freeing the Yamuna from her poison. The river ran clear again, the birds returned to sing, and the gopis drew water with joy — for where Krishna steps, even poison becomes nectar, and even the darkest heart finds the light of redemption.",
  },
  {
    title: "Putana Vadh",
    body: "In the dark chambers of Kansa's palace, the cruel king hatched yet another plot to kill the child who had been prophesied to end his reign. He sent Putana, a fearsome demoness who could change her form at will, to the peaceful homes of Gokul disguised as a beautiful, gentle nurse with poison smeared upon her breast. Putana entered Yashoda's home with honeyed words and outstretched arms, offering to nurse the infant Krishna with a smile as sweet as death itself. Little did she know that the child she held was no ordinary baby — He was the Lord of all creation, the one who drinks the poison of the cosmos and transforms it into bliss. As Putana offered her poisoned breast, baby Krishna suckled with such force that He drew not only her milk but her very life-force, growing larger and larger while she shrank in terror. The demoness dropped her disguise and revealed her true monstrous form, a hundred miles long, crashing through trees and houses as her life ebbed away. With her last breath, she looked upon the Divine Infant with pure devotion, and Krishna granted her liberation — for even the greatest sinner, when they turn to Him with surrender, finds the door to eternity. The gopis woke to find the gigantic corpse of Putana, and little Krishna playing upon her chest as if on a mother's lap, teaching the world that His embrace destroys only the darkness within us.",
  },
  {
    title: "Sudama's Handful of Poha",
    body: "In a humble hut made of mud and thatch, lived Sudama, a poor brahmin who had once been Krishna's dearest friend in the gurukul of Sandipani Muni. Years had passed since those golden days of childhood, and now Sudama's clothes were tattered, his ribs showed through his skin, and his children cried from hunger in the night. His wife, with tears in her eyes, begged him to go to Dwarka and ask their old friend, now the mighty king of kings, for some small help. Sudama refused to ask for anything, but agreed to visit his beloved Krishna, carrying as a gift a small bundle of beaten rice wrapped in a torn cloth — all they had in the house. When Sudama reached the golden gates of Dwarka, guards laughed at his poverty, but word reached Krishna, and the Lord of the universe ran barefoot through the palace halls to embrace His childhood friend. Krishna, the king of the Yadavas, ate that humble poha with tears of love streaming down His cheeks, declaring it the sweetest feast He had ever tasted. He washed Sudama's feet with His own hands, fed him a royal banquet, and sent him home with joy in his heart — but not a single coin or jewel. Yet when Sudama returned home, he found his mud hut transformed into a palace of marble and gold, his family clothed in silk, and his barns overflowing with grain. For the Lord measures not the gift, but the love with which it is given, and Sudama's torn bundle of poha was richer than all the treasures of Indra.",
  },
  {
    title: "The Raas under the Moon",
    body: "On the autumn night of Sharad Purnima, when the full moon hung over Vrindavan like a silver lamp and the Yamuna whispered secrets to the Kadamba trees, Krishna stood upon the riverbank and lifted His flute to His lips. The music that poured forth was not of this world — it was the call of the soul to the Divine, the ancient song that had echoed since the first star was born. The gopis, hearing that flute, dropped their pots of milk, left their half-cooked meals, abandoned their sleeping children, and ran through the forest without looking back. Their families called after them, the village elders shook their heads, but nothing could stop the feet that were drawn by love itself. When they reached the forest clearing, Krishna stood waiting, and He began to dance — not one dance, but a thousand dances at once. Each gopi felt Krishna dancing with her alone, His hand in hers, His eyes looking only into her soul, His smile meant for her alone. The peacocks danced, the deer watched in wonder, and the moon itself seemed to pause in the sky to witness this divine love-play. This was the Raas — the eternal dance of the soul and the Supreme, where separation dissolves in union and the individual self loses itself in the ocean of divine bliss. When dawn finally came, the gopis returned to their homes, their hearts overflowing, knowing that the One they loved was not merely a boy of Vrindavan — He was the heartbeat of the universe itself, calling every soul to His eternal dance.",
  },
  {
    title: "Draupadi's Endless Saree",
    body: "In the great hall of Hastinapur, where the Kauravas had gathered to humiliate the Pandavas after winning them in a rigged game of dice, the air grew thick with cruelty and pride. Dushasana, the wicked brother of Duryodhana, seized Draupadi by her hair and dragged her into the center of the court, laughing as the elders sat in cowardly silence. He began to pull at her saree, yard after yard of cloth, while the assembled kings watched in shame and Draupadi's five husbands hung their heads in helpless rage. With each tug, her modesty hung by a thread, her tears fell like monsoon rain, and her voice rose in a single, desperate cry that pierced the walls of the palace and traveled across kingdoms — 'Govinda!' In distant Dwarka, Krishna was at His breakfast when He heard that cry, that single tear, that one whisper of His name spoken in absolute surrender. He did not need to travel, He did not need to raise a weapon — He simply extended His grace like an endless river of cloth. As Dushasana pulled, the saree grew without end, yard upon yard upon yard, until the hall was buried in fabric and the demon brother's arms grew tired and his pride turned to dust. Krishna had not been present in body, but He was more present than anyone in that hall — teaching the world that when you call His name with a pure heart, even from the darkest pit of humiliation, He hears you before the sound leaves your lips. Draupadi stood fully clothed, radiant with divine protection, while Dushasana sat exhausted and defeated — for the Lord's mercy has no end, and His protection has no limit.",
  },
  {
    title: "Kansa Vadh",
    body: "For years, the tyrant Kansa had ruled Mathura with an iron fist, crushing all who opposed him and drowning the land in fear. When he learned that the eighth child of his sister Devaki would be his doom, he imprisoned the couple and murdered their first seven infants one by one, each death a fresh wound in Devaki's shattered heart. But when the eighth child was born — at midnight, in a prison cell, with the guards mysteriously asleep and the doors unchained — the Divine Infant appeared in His four-armed form, holding the conch, discus, mace, and lotus. Vasudeva carried the baby through the night, across the flooded Yamuna that parted like a sea of devotion, and placed Him in the safe arms of Yashoda in Gokul. Years passed, and Krishna grew in strength and beauty, performing leela after leela that echoed across the land. Finally, Kansa summoned Krishna and Balarama to Mathura for a wrestling tournament, hoping to have them killed by his mighty champions. But Krishna, barely a youth, defeated the wrestlers with ease, and when Kansa drew his sword in rage, Krishna leaped onto the throne and struck the tyrant down with a single blow. Yet even in death, Kansa was blessed — for he had been touched by the Lord's hand, and his soul was released from the cycle of birth and death. The people of Mathura erupted in joy, the prison doors were thrown open, and Devaki and Vasudeva wept with relief — for the Lord had kept His promise, and even the instrument of evil becomes a vessel of liberation when it serves the divine plan.",
  },
  {
    title: "Krishna as Sarathi at Kurukshetra",
    body: "On the vast battlefield of Kurukshetra, where eighteen armies stood facing each other and the air smelled of dust and impending death, Arjuna the great warrior suddenly found his hands trembling and his bow Gandiva slipping from his fingers. He looked upon the rows of his cousins, his teachers, his childhood friends, and his heart broke — how could he kill those he loved for the sake of a kingdom? He turned to Krishna, who sat not upon a throne but upon the chariot driver's seat, holding the reins of Arjuna's horses with the same hands that had lifted Govardhan and played the flute of Vrindavan. The Lord of the universe, the source of all creation, had chosen to be a humble charioteer for His friend — not because He needed to, but because He wanted to teach the world that the greatest service is done in humility. For eighteen days, Krishna guided that chariot through showers of arrows and seas of blood, steering His friend not just across the battlefield but through the battlefield of doubt, fear, and despair. And in the very first moments, before a single arrow was fired, Krishna delivered the song that would echo through eternity — the Bhagavad Gita, the divine discourse that has guided every seeker since. He did not fight Arjuna's battle for him; He did not remove the difficulty; He simply sat beside him, held the reins, and whispered the truth that burns away all darkness. This is the Lord's way — He does not always calm the storm, but He always calms the sailor.",
  },
  {
    title: "Bal Krishna and Yashoda",
    body: "In the quiet courtyard of Yashoda's home, where clay pots lined the walls and the smell of fresh ghee filled every corner, the foster mother of God lived a life of pure, unending devotion. She did not know that the dark-skinned boy tugging at her apron was the Lord of infinite universes — to her, He was simply her Kanha, the child who ate too much butter and broke too many pots. One day, after little Krishna had raided a neighbor's butter stash yet again, Yashoda chased Him with a stick, her eyes blazing with mock anger and her heart bursting with love. She caught Him and tied Him to a heavy grinding mortar with a rope, but no matter how many ropes she added, they always fell short by two finger-widths — for the infinite cannot be bound by the finite. As Krishna dragged that mortar between two giant Arjuna trees, they crashed to the ground, and two celestial beings emerged, freed from a long curse. Yashoda ran to her son in terror, but when she looked into His eyes, she saw not a mischievous child but the entire cosmos — stars, galaxies, oceans, mountains, and all of time itself swirling in those dark pupils. She gasped and drew back, overwhelmed, but Krishna smiled and the vision faded, leaving only her little boy once more. For the Lord reveals His true form only for a moment, just enough to remind us of who He truly is, before hiding again in the simple beauty of everyday love. Yashoda held Him close, tears streaming down her face, knowing and not knowing, seeing and not seeing — for that is the mystery of devotion, where the mother holds the Creator and thinks herself the protector.",
  },
  {
    title: "Akrura's Journey to Vrindavan",
    body: "Akrura, the noble minister of Kansa, had been sent on a mission he did not wish to undertake — to bring Krishna and Balarama from Vrindavan to Mathura, where the tyrant king planned to have them killed. As he rode his chariot through the golden fields and past the Yamuna's gentle curves, his heart grew heavier with every mile, for he was a secret devotee of the Lord and knew the danger that awaited. When he reached the Yamuna to bathe before entering Vrindavan, the river revealed a vision that stopped his breath — he saw Krishna resting upon the serpent Shesha in the cosmic ocean, the entire universe blooming from His body, and all the gods paying homage to that formless form. Tears streamed down Akrura's face as he understood that the boy he was to escort was no ordinary soul but the source of all existence. He entered Vrindavan with trembling hands and a heart full of devotion, and when he saw Krishna and Balarama walking toward him like two clouds of beauty and strength, he fell to the ground in surrender. The brothers embraced him with such warmth that all his fears melted away, and he returned with them to Mathura not as a captor but as a pilgrim who had seen the Divine. Akrura's story teaches us that even those who seem to serve evil are sometimes secret devotees, waiting for the moment when grace opens their eyes — for the Lord sees the devotion hidden in the heart, even when the hands are bound by duty.",
  },
  {
    title: "Narad and Krishna's 16108 Queens",
    body: "When the great sage Narada heard that Krishna, the Supreme Lord, had married 16108 queens in His palace at Dwarka, his scholarly mind was puzzled — how could the enlightened One, the yogi of yogis, be so entangled in worldly relationships? Determined to understand this mystery, Narada traveled to Dwarka and arrived at the magnificent palace of Krishna and His queen Rukmini. He was welcomed with royal honor, offered the finest food, and engaged in deep spiritual conversation, but as the day wore on, he noticed something strange. Krishna seemed distracted, as if His mind were elsewhere, and when Narada finally took his leave, he decided to visit another of Krishna's palaces. To his utter astonishment, he found Krishna there too, playing with children, discussing philosophy with scholars, and sharing tender moments with another queen — and in every palace he visited, the same Krishna stood in a different form, fulfilling a different role with complete presence and love. Narada's eyes filled with tears as the truth dawned upon him — Krishna was not divided; He was multiplied in love, present fully with each devotee as if they were His only one. The 16108 queens were not a symbol of worldly indulgence but of the Lord's infinite capacity to love each soul completely, without measure, without division. Narada bowed before this mystery and sang the glories of the One who is many, the undivided who divides Himself only to gather every heart into His embrace.",
  },
  {
    title: "The Syamantaka Jewel",
    body: "In the golden city of Dwarka, there lived a jewel called the Syamantaka, gifted by the sun god to Satrajit, which had the power to produce eight loads of gold every day and protect its owner from all calamities. When this jewel was stolen one dark night, the people of Dwarka whispered that Krishna, known for His love of beauty, must be the thief. Krishna, hearing the false accusation, accepted it with a gentle smile and set out to clear His name through His own effort. He tracked the jewel through dense forests and rocky caves, following clues that led Him deeper into a mystery wrapped in deception. The trail led to a bear named Jambavan, an ancient devotee of Rama who had found the jewel and given it to his daughter as a toy. When Krishna fought Jambavan for many days, the bear finally recognized the Lord in His new form and, with tears of joy, surrendered the jewel along with his daughter Jambavati in marriage. Krishna returned to Dwarka with the Syamantaka, cleared His name, and restored peace — but more importantly, He won the heart of a devotee who had been waiting ages to see his beloved Lord again. This story reminds us that the Lord allows false accusations to fall upon Him so that He may seek out the lost, recover the stolen, and turn every misunderstanding into a reunion of love.",
  },
  {
    title: "Rukmini Haran",
    body: "In the kingdom of Vidarbha, Princess Rukmini was known throughout the land for her beauty that rivaled the goddess Lakshmi and her devotion that burned brighter than a thousand lamps. Her brother Rukmi, arrogant and ambitious, had arranged her marriage to Shishupal, a prince of evil nature, against her deepest wishes — for Rukmini's heart had been given long ago to Krishna, whom she had loved through lifetimes of longing. On the eve of the wedding, Rukmini sent a secret messenger to Dwarka with a letter written in tears, begging Krishna to come and rescue her from a fate worse than death. Krishna, reading her words, felt the pull of a soul that had surrendered completely, and He mounted His chariot with His brother Balarama by His side. As the wedding procession made its way through the streets, Rukmini stood at the temple of Goddess Gauri, her hands folded in prayer, her eyes searching the horizon with a heart that beat only for one name. Suddenly, the crowds parted, Krishna's chariot thundered into view, and before anyone could raise a weapon, He lifted Rukmini into His arms and swept her away as easily as the wind carries a fallen petal. The armies of Rukmi gave chase, but Balarama defeated them with ease, and the couple was married in Dwarka with celebrations that lasted for days. Rukmini's elopement was not a theft but a rescue — for when the soul cries out to the Lord with genuine surrender, He crosses every boundary, defeats every army, and claims His beloved with a love that is both fierce and tender.",
  },
  {
    title: "Shishupal Vadh",
    body: "In the grand court of Yudhishthira's Rajasuya yagna, kings and sages from across the world had gathered to honor the eldest Pandava, and Bhishma declared that Krishna should receive the highest worship as the supreme being. But from the crowd rose Shishupal, king of Chedi, his face twisted with envy and his voice dripping with poison, for he harbored a lifelong hatred of Krishna born from a forgotten curse in a previous birth. One by one, he hurled a hundred insults at the Lord, mocking His birth, His deeds, His relationships, each word sharper than a sword, each accusation more vile than the last. The Pandavas trembled with rage, Balarama's hand went to His plough, but Krishna sat upon His throne, a gentle smile upon His lips, counting each insult like a treasurer counting jewels. For Krishna had promised Shishupal's mother that He would forgive a hundred offenses, and the Lord keeps His word even to His enemies. But when the hundred and first insult left Shishupal's lips, Krishna raised His Sudarshan Chakra, that wheel of blazing fire that has spun since the dawn of time, and with a single motion sent it flying through the hall. The chakra pursued Shishupal like justice pursues falsehood, and in an instant, the hateful king fell, his body returned to the light from which it came. Yet even in death, Shishupal was liberated — for the Lord had counted his insults as if they were prayers, and the hundred and first word had completed the devotion hidden within a lifetime of hatred. Thus Krishna teaches us that He accepts even the anger of His enemies and transforms it into liberation, for all paths, when they reach Him, become paths of grace.",
  },
  {
    title: "The Birth in Kansa's Prison",
    body: "On the darkest night of the year, when rain fell in sheets and the wind howled like a beast through the streets of Mathura, Devaki and Vasudeva sat chained in the deepest dungeon of Kansa's prison. Seven times they had heard the cry of a newborn silenced forever, seven times they had watched their children torn from their arms by the cruel king who feared a prophecy. But this eighth birth was different — the guards fell into a sleep deeper than death, the iron chains melted like butter in the sun, and the prison doors swung open of their own accord. Devaki gave birth not to an ordinary child but to the Lord of all creation, who appeared in His four-armed form holding the conch, the discus, the mace, and the lotus, His body dark as a raincloud and beautiful as a thousand moons. Vasudeva, weeping with joy and wonder, placed the infant in a basket and walked through the open gates, past the sleeping guards, and into the storm. The Yamuna, seeing her Lord approach, rose in towering waves but then parted completely, creating a dry path through her waters, while the great serpent Shesha spread his hoods over the basket like a divine umbrella. In Gokul, Vasudeva found Yashoda sleeping with a newborn girl, and when he placed Krishna in her arms and took the girl back to the prison, the doors closed behind him and the guards awoke as if from a dream. Kansa burst into the cell, seized the girl, and hurled her against the stone wall — but she rose into the air as the goddess Yogamaya, laughing as she told the tyrant that his slayer was safe in Gokul. The prophecy was set in motion, and the darkness of Kansa's reign had already begun to crack, for when the Lord descends, even the thickest prison walls become doorways to freedom.",
  },
  {
    title: "Krishna and the Fruit Seller",
    body: "In the bustling marketplace of Gokul, where vendors cried their wares and the smell of jaggery filled the air, an old fruit seller sat beneath a tamarind tree with her baskets of ripe mangoes and sweet berries. Little Krishna, His dark skin glowing in the morning sun, ran to her with a handful of freshly husked rice grains — the only currency a child of the cowherds possessed. The old woman's eyes softened at the sight of the beautiful boy, and she filled His small hands with the sweetest fruits she had, accepting the rice with a mother's love rather than a merchant's calculation. As she watched Him run away, laughing and calling to His friends, she noticed something strange — her baskets, which should have been empty, were overflowing with jewels brighter than any she had ever seen. She wept, understanding that the Lord had come to her in the form of a child, and that His handful of rice had been worth more than all the treasures of the earth. From that day, she never sold another fruit — she gave them away to every child who passed, hoping to see those lotus eyes once more. The story spread through Vrindavan, and mothers began to look differently at the children who came to their doors, wondering if behind each face might be hidden the smile of the Divine. For Krishna does not come only in temples and scriptures — He comes in the marketplace, in the eyes of the poor, in the hands of a fruit seller who gives without counting, teaching us that every exchange of love is a transaction with God Himself.",
  },
  {
    title: "The Gopis' Search — Uddhava's Message",
    body: "When Krishna left Vrindavan for Mathura, the gopis felt as if the sun had been stolen from their sky, leaving them in a darkness that no lamp could dispel. Days became years, and their love did not diminish but grew like a fire that feeds on its own flames, consuming everything except devotion. One day, Uddhava, Krishna's closest friend and counselor, arrived in Vrindavan with messages of love from Dwarka, expecting to find broken women and a village mourning its loss. Instead, he found the gopis singing Krishna's name in the forests, drawing His footprints in the dust, and speaking to the trees and rivers as if they were old friends who had also known His touch. He tried to teach them philosophy, to explain that the Lord is everywhere and that separation is merely an illusion of the mind. But the gopis laughed gently and told him that they knew all this — they knew Krishna was in every atom of creation, but that knowledge did not satisfy the heart that had once held His hand. They spoke of the flute that no longer played by the Yamuna, the cows that lowed in sadness, and the empty pathways where His footprints had once danced. Uddhava, the great scholar, found himself the student in that forest, learning from simple village women that love transcends knowledge, that devotion is greater than philosophy, and that the heart that cries for God is nearer to Him than the mind that explains Him. He returned to Krishna with tears in his eyes and a new understanding — that the gopis of Vrindavan, in their madness of love, had reached a height that even the gods could only aspire to.",
  },
  {
    title: "The Curse of the Brahmins and Dwarka's Rise",
    body: "When the Yadava clan was cursed by the sages Gandhari and the visiting brahmins that they would destroy each other and their city would sink into the sea, Krishna knew that the time had come for the end of His earthly leela. But before that darkness fell, He had built Dwarka as a city of such beauty that even the gods looked down in wonder — a city risen from the ocean by the grace of the Lord, with golden streets and jeweled palaces, where dharma flourished and every citizen lived in prosperity. For years, Dwarka shone like a second heaven upon the earth, a testament to what the world could be when ruled by wisdom and love rather than greed and power. Krishna walked those golden streets not as a distant king but as a friend to every citizen, resolving disputes with a smile, feeding the hungry from His own kitchens, and playing with the children as if He had no kingdom to govern. The curse, however, was already weaving its web — the pride of the Yadavas grew with their prosperity, and small quarrels began to fester beneath the surface of that golden peace. When the end came, it came suddenly — a drunken brawl at a festival turned into a massacre, and cousins who had grown up together struck each other down with the very clubs that had once been toys. Krishna watched the destruction with a heart heavy with love, knowing that every end is also a beginning, and that the sinking of Dwarka was not a defeat but a return — the leela completing its circle, the actors leaving the stage so that the play may begin again. As the ocean swallowed the golden city, the Lord's flute fell silent, but its music did not end — it simply moved into the hearts of those who would remember, generation after generation, until the end of time.",
  },
  {
    title: "The Final Leela and Return to Vaikuntha",
    body: "In the quiet forest of Prabhasa, where the remnants of the Yadava clan had gathered in mourning and confusion, Krishna sat beneath a peepal tree in deep meditation, His dark form radiant even in the fading light of that age. A hunter named Jara, mistaking the Lord's foot for the ear of a deer, shot a single arrow that pierced the heel — the only vulnerable spot in a body that had contained the infinite. Jara ran forward in horror, falling at the feet of the dying Lord, weeping and begging forgiveness for the greatest sin a man could commit. But Krishna smiled, took the hunter's hand in His own, and blessed him — for this too was leela, the final act of a play that had begun long before the first star was born. The Lord had allowed Himself to be 'killed' so that the world could learn that even the body of God is perishable, but the soul of God is eternal. As Krishna's form returned to the infinite light of Vaikuntha, the earth trembled, the seas rose, and the gods wept in heaven, for they knew that an age of darkness had begun with the departure of the light. Arjuna, arriving too late, fell upon the earth in grief, understanding at last that all his strength, all his victories, all his friendships had been borrowed from the One who now lay still beneath the tree. Yet even in that darkest moment, a whisper remained in the wind, a smile in every flower, a flute-note in every bird's song — for Krishna does not truly leave. He simply changes His form, becoming the love in the devotee's heart, the dharma in the seeker's path, and the promise that one day, in some lifetime, in some forest, the flute will play again and the dance will resume. This is the final leela — not an ending, but an eternal beginning, a return that is also an arrival, a goodbye that is really 'until we meet again.'",
  },
];

function getPreview(body: string): string {
  const sentences = body.match(/[^.!?]+[.!?]+/g) || [body];
  return sentences.slice(0, 3).join(" ").trim();
}

const LeelaStories = () => {
  const [expanded, setExpanded] = useState<Set<number>>(new Set());

  const toggle = (i: number) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });
  };

  return (
    <PageShell title="Leela Stories" subtitle="The endless play of the Lord">
      <div className="space-y-5">
        {STORIES.map((s, i) => {
          const isOpen = expanded.has(i);
          const preview = getPreview(s.body);
          return (
            <article
              key={i}
              className="rounded-3xl glass-strong border border-[hsl(var(--divine-gold)/0.3)] p-6 sm:p-7 hover:border-[hsl(var(--divine-gold)/0.55)] transition-colors"
            >
              <p className="text-[10px] tracking-[0.3em] uppercase text-primary/55 mb-2">
                Leela {String(i + 1).padStart(2, "0")}
              </p>
              <h2
                className="font-display text-xl sm:text-2xl text-transparent bg-clip-text bg-gradient-to-r from-[hsl(var(--divine-gold))] to-primary mb-3"
                style={{ fontFamily: "'Cinzel', 'Playfair Display', serif" }}
              >
                {s.title}
              </h2>
              <p className="font-body text-[15px] leading-[1.75] text-foreground/85">
                {isOpen ? s.body : preview}
              </p>
              <button
                onClick={() => toggle(i)}
                className="mt-4 inline-flex items-center gap-1.5 text-[13px] font-medium tracking-wide uppercase text-[hsl(var(--divine-gold))] hover:text-primary transition-colors"
              >
                {isOpen ? "Read Less" : "Read More"}
                <span
                  className="inline-block transition-transform duration-300"
                  style={{ transform: isOpen ? "rotate(180deg)" : "rotate(0deg)" }}
                >
                  ↓
                </span>
              </button>
            </article>
          );
        })}
      </div>
    </PageShell>
  );
};

export default LeelaStories;
